development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "ENV['RDS_URL']" } %>
  channel_prefix: chatroomapps_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "ENV['RDS_URL']" } %>
  channel_prefix: chatroomapps_production
